<!DOCTYPE html>
<html>
<head>
    <style>
        @page { margin: 100px 50px; }
        body { font-family: 'Helvetica', sans-serif; color: #1e293b; }
        .header { position: fixed; top: -60px; left: 0; right: 0; text-align: center; border-bottom: 2px solid #f1f5f9; padding-bottom: 20px; }
        .footer { position: fixed; bottom: -60px; left: 0; right: 0; text-align: center; font-size: 10px; color: #94a3b8; }
        .title { font-size: 24px; font-weight: bold; color: #0f172a; margin-bottom: 5px; }
        .subtitle { font-size: 12px; color: #64748b; text-transform: uppercase; letter-spacing: 1px; }
        
        .section-title { font-size: 14px; font-weight: bold; text-transform: uppercase; color: #4f46e5; margin: 30px 0 15px; border-left: 4px solid #4f46e5; padding-left: 10px; }
        
        .metrics-grid { width: 100%; margin-bottom: 30px; }
        .metric-box { padding: 20px; background: #f8fafc; border-radius: 12px; border: 1px solid #e2e8f0; }
        .metric-label { font-size: 10px; font-weight: bold; color: #94a3b8; text-transform: uppercase; }
        .metric-value { font-size: 22px; font-weight: bold; color: #0f172a; }
        
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th { padding: 12px 15px; background: #f1f5f9; text-align: left; font-size: 10px; font-weight: bold; text-transform: uppercase; color: #64748b; }
        td { padding: 12px 15px; border-bottom: 1px solid #f1f5f9; font-size: 12px; }
        .text-right { text-align: right; }
        .total-row { background: #f8fafc; font-weight: bold; }
        
        .badge { padding: 4px 8px; border-radius: 6px; font-size: 10px; font-weight: bold; }
        .badge-indigo { background: #eef2ff; color: #4338ca; }
    </style>
</head>
<body>
    <div class="header">
        <div class="title">Payroll Disbursement Insight</div>
        <div class="subtitle">AISAT College • Statistical Report</div>
    </div>

    <div class="footer">
        Generated by System on {{ now()->format('F d, Y h:i A') }} • Page <span class="pagenum"></span>
    </div>

    <div class="section-title">Institutional Summary</div>
    <table class="metrics-grid">
        <tr>
            <td class="metric-box" width="48%">
                <div class="metric-label">Total Payout for Period</div>
                <div class="metric-value">₱{{ number_format($totalPayout, 2) }}</div>
            </td>
            <td width="4%"></td>
            <td class="metric-box" width="48%">
                <div class="metric-label">Active Headcount</div>
                <div class="metric-value">{{ $activeEmployees }} Personnel</div>
            </td>
        </tr>
    </table>

    <div class="section-title">Department Distribution</div>
    <table>
        <thead>
            <tr>
                <th>Department</th>
                <th>Employee Count</th>
                <th class="text-right">Total Investment</th>
                <th class="text-right">% of Budget</th>
            </tr>
        </thead>
        <tbody>
            @foreach($deptSummary as $dept)
            <tr>
                <td><span class="badge badge-indigo">{{ strtoupper($dept['name']) }}</span></td>
                <td>{{ $dept['count'] }} Personnel</td>
                <td class="text-right">₱{{ number_format($dept['total'], 2) }}</td>
                <td class="text-right">{{ number_format(($dept['total'] / max(1, $totalPayout)) * 100, 1) }}%</td>
            </tr>
            @endforeach
            <tr class="total-row">
                <td colspan="2">GRAND TOTAL</td>
                <td class="text-right">₱{{ number_format($totalPayout, 2) }}</td>
                <td class="text-right">100.0%</td>
            </tr>
        </tbody>
    </table>

    <div class="section-title" style="margin-top: 50px;">Lateness Analytics</div>
    <p style="font-size: 12px; color: #64748b;">
        Total deductions for lateness in this period amounted to <strong>₱{{ number_format($totalDeductions, 2) }}</strong>. 
        This represents performance-related adjustments based on the primary institutional schedule.
    </p>

</body>
</html>
