services:
  - type: web
    name: payroll-system
    runtime: docker
    plan: free # Change to 'starter' if you need more resources
    region: singapore # Change to your preferred region (ohio, frankfurt, oregon, singapore)
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        fromService:
          name: payroll-system
          type: web
          property: host
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "3306"
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: MYSQL_ATTR_SSL_CA
        value: /app/ca.pem
      - key: LOG_CHANNEL
        value: errorlog
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
